name: Deploy rfitness

on:
  push:
    branches:
      - "my-prod"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shahidshabbir-se/rfitness:latest
            ghcr.io/shahidshabbir-se/rfitness:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" > ./envfile

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Setup SSH Tunnel with Retry
        run: |
          until ssh -N -L 5432:${{ secrets.DATABASE_HOST }}:5432 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} -i ~/.ssh/deploy_key; do
            echo "Retrying SSH tunnel setup..."
            sleep 5
          done
        continue-on-error: false

      - name: Apply Prisma Migrations
        run: |
          npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://postgres:${{ secrets.DATABASE_PASSWORD }}@127.0.0.1:5432/app?schema=public"

      - name: Deploy with Docker Stack
        uses: cssnr/stack-deploy-action@v1
        with:
          name: rfitness
          file: docker-stack.yml
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USER }}
          ssh_key: ~/.ssh/deploy_key
          env_file: ./envfile
